version: 2
updates:
  - directory: "/"
    package-ecosystem: "gradle"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - directory: "/application"
    package-ecosystem: "gradle"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
  - directory: "/library"
    package-ecosystem: "gradle"
    open-pull-requests-limit: 10
    schedule:
      interval: "daily"
