#!/bin/sh

commit_regex='(\#(\d{6,8}|NA|na) \[\w.*\] .*)'
error_msg="Aborting commit. commit message is either '#123456 [PairA & PairB] commit message' or '#NA [PairA] infra' "

if ! grep -iqE "$commit_regex" "$1"; then
    echo "$error_msg" >&2
    exit 1
fi
